/**
 * @file CanBus.cpp
 * @brief Linux SocketCAN implementation of @ref aeb::CanBus.
 */

#include "canbus/CanBus.hpp"

#include <cerrno>
#include <cstdio>
#include <cstring>
#include <string>

#include <arpa/inet.h>
#include <linux/can.h>
#include <linux/can/raw.h>
#include <net/if.h>
#include <netinet/in.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <unistd.h>

namespace aeb {
namespace {

/**
 * @brief Format an error string from @c errno.
 * @param context Brief description of the failing operation.
 * @return Human-readable string.
 */
std::string describeErrno(const std::string& context)
{
    return context + ": " + std::strerror(errno);
}

/** @brief Localhost address the App Lab can-bridge TCP server listens on. */
constexpr const char* kUnoQBridgeHost = "127.0.0.1";

/** @brief Port the App Lab can-bridge TCP server listens on. */
constexpr std::uint16_t kUnoQBridgePort = 39001U;

}  // namespace

CanBus::CanBus(CanBusConfig config) : config_{std::move(config)} {}

CanBus::~CanBus()
{
    close();
}

bool CanBus::open()
{
    if (fd_ >= 0) {
        last_error_ = "already open";
        return false;
    }

    if (config_.use_fifo_transport) {
        // UNO Q mode: the AEB CAN logic is unchanged; only the transport is a
        // localhost TCP connection to the App Lab can-bridge application
        // instead of a SocketCAN interface.
        fd_ = ::socket(AF_INET, SOCK_STREAM, 0);
        if (fd_ < 0) {
            last_error_ = describeErrno("socket(AF_INET)");
            fd_ = -1;
            return false;
        }

        sockaddr_in addr{};
        addr.sin_family = AF_INET;
        addr.sin_port = ::htons(kUnoQBridgePort);
        if (::inet_pton(AF_INET, kUnoQBridgeHost, &addr.sin_addr) != 1) {
            last_error_ = std::string{"invalid UNO Q bridge address "} + kUnoQBridgeHost;
            ::close(fd_);
            fd_ = -1;
            return false;
        }

        if (::connect(fd_, reinterpret_cast<struct sockaddr*>(&addr), sizeof(addr)) < 0) {
            last_error_ = describeErrno(std::string{"connect("} + kUnoQBridgeHost + ":" +
                                        std::to_string(kUnoQBridgePort) +
                                        ") - is the App Lab can-bridge app running?");
            ::close(fd_);
            fd_ = -1;
            return false;
        }

        last_error_.clear();
        return true;
    }

    fd_ = ::socket(PF_CAN, SOCK_RAW, CAN_RAW);
    if (fd_ < 0) {
        last_error_ = describeErrno("socket(PF_CAN)");
        fd_ = -1;
        return false;
    }

    struct ifreq ifr{};
    if (config_.interface.size() >= IFNAMSIZ) {
        last_error_ = "interface name too long: " + config_.interface;
        ::close(fd_);
        fd_ = -1;
        return false;
    }
    std::strncpy(ifr.ifr_name, config_.interface.c_str(), IFNAMSIZ - 1U);

    if (::ioctl(fd_, SIOCGIFINDEX, &ifr) < 0) {
        last_error_ = describeErrno("ioctl(SIOCGIFINDEX) on " + config_.interface);
        ::close(fd_);
        fd_ = -1;
        return false;
    }

    struct sockaddr_can addr{};
    addr.can_family  = AF_CAN;
    addr.can_ifindex = ifr.ifr_ifindex;

    if (::bind(fd_, reinterpret_cast<struct sockaddr*>(&addr), sizeof(addr)) < 0) {
        last_error_ = describeErrno("bind on " + config_.interface);
        ::close(fd_);
        fd_ = -1;
        return false;
    }

    last_error_.clear();
    return true;
}

void CanBus::close() noexcept
{
    if (fd_ >= 0) {
        ::close(fd_);
        fd_ = -1;
    }
}

bool CanBus::send(const CanMessage& msg) noexcept
{
    if (fd_ < 0) {
        return false;
    }

    if (config_.use_fifo_transport) {
        // Deterministic text format for the App Lab can-bridge TCP server:
        // "<id> <dlc> <byte>...\n". Only the valid (dlc) bytes are
        // serialised; the CanMessage generated by the existing AEB logic is
        // otherwise untouched.
        char line[64];
        const std::uint8_t bytes = (msg.dlc <= kCanMaxDlc) ? msg.dlc : kCanMaxDlc;
        int len = std::snprintf(line, sizeof(line), "%u %u", msg.id, static_cast<unsigned>(bytes));
        for (std::uint8_t i = 0U; len > 0 && static_cast<std::size_t>(len) < sizeof(line) && i < bytes; ++i) {
            len += std::snprintf(line + len, sizeof(line) - static_cast<std::size_t>(len), " %u",
                                 static_cast<unsigned>(msg.data[i]));
        }
        if (len <= 0 || static_cast<std::size_t>(len) >= sizeof(line) - 1U) {
            return false;  // Malformed or would overflow the line buffer.
        }
        line[len++] = '\n';

        const ssize_t sent = ::send(fd_, line, static_cast<std::size_t>(len), MSG_DONTWAIT);
        return sent == static_cast<ssize_t>(len);
    }

    struct can_frame frame{};
    frame.can_id  = msg.id;
    frame.can_dlc = msg.dlc;
    const std::uint8_t bytes = (msg.dlc <= kCanMaxDlc) ? msg.dlc : kCanMaxDlc;
    std::memcpy(frame.data, msg.data, bytes);

    const ssize_t sent = ::send(fd_, &frame, sizeof(frame), MSG_DONTWAIT);
    return sent == static_cast<ssize_t>(sizeof(frame));
}

bool CanBus::isOpen() const noexcept
{
    return fd_ >= 0;
}

const std::string& CanBus::lastError() const noexcept
{
    return last_error_;
}

}  // namespace aeb
